### ISSUE TITLE
Divide the Post component into different reusable components

### ISSUE THREAD

**Issue by Nanak360** [Nanak360/Connectopia#7]
Currently, the Post component is not divided into components.
It should be divided into components for better reusability of code.
Checkout this [file](https://github.com/Nanak360/Connectopia/blob/main/components/Post/index.jsx)

### Interact component: 
``` 
     <div className="mt-5 flex gap-6 items-center">
        <button className="flex gap-1 items-center">
          <Heart /> 1.2k
        </button>
        <button className="flex gap-1 items-center">
          <MessageCircle /> 221
        </button>
        <button className="flex gap-1 items-center">
          <Share2 /> 91
        </button>
      </div>
```

and there are many other things like comments and header section that can be moved to their separate components

**Comment by Aryan123-rgb** [comment]
Kindly assign it to me. But before that here's what I will do.
1. Create a new branch
2. Make necessary changes
3. Create a pull request
If there is a specific norm I need to follow tell me beforehand

**Comment by Nanak360** [comment]
@Aryan123-rgb 
Yeah this is the norm that needs to be followed
But don't forget to create a fork and raise a PR from your fork's branch
Don't raise PR directly without forking
